### ISSUE TITLE
Which ur_description pkg?

### ISSUE THREAD

**Issue by JavaJeremy** [TAMS-Group/tams_ur5#5]
I'm getting an error from `ur5.urdf.xacro` at runtime: 
> resource not found: ur_description  

Would be great if someone could add more information about this, where/how to get that resource for instance, can't find anything about it here.

**Comment by JavaJeremy** [comment]
Found it, it's in https://github.com/TAMS-Group/universal_robot
Maybe it could be mentioned in a "Dependencies"-Part in the readme just like the dependencies are listed in the Bartender-Pkg. Also I think Robotiq (https://github.com/ros-industrial/robotiq) is another dependency needed.

**Comment by v4hn** [comment]
We have https://github.com/TAMS-Group/rosinstalls/blob/master/kinetic-tams_ur5-setup%2Bpick-place.rosinstall
for this setup, but apparently it is outdated (it still lists ros-industrial's universal_robot package).

As far as I know, we currently require this branch:
https://github.com/TAMS-Group/universal_robot/tree/ros-industrial-kinetic_lookup-param

Please file a pull-request to update the rosinstall file.
