### ISSUE TITLE
xacro:include: unknown attribute(s): prefix

### ISSUE THREAD

**Issue by lianghongzhuo** [TAMS-Group/tams_ur5#9]
I always saw a warning like this `xacro:include: unknown attribute(s): prefix`.
Now I have time to look it up.
In file [here](https://github.com/TAMS-Group/tams_ur5/blob/master/tams_ur5_description/urdf/ur5.urdf.xacro#L93) we can see it already defined the attribute `prefix`. Why `xacro` still complain about it?

**Comment by v4hn** [comment]
Could you give the full error message?
The line you quote is about `include`, not about `macro` as far as I can see?

**Comment by lianghongzhuo** [comment]
Here is the full warning message:
```
xacro: in-order processing became default in ROS Melodic. You can drop the option.
redefining global property: pi
when processing file: */src/tams/tams_ur5_setup/tams_ur5_setup_description/urdf/tams_ur5_setup.urdf.xacro
redefining global property: pi
when processing file: */src/tams/tams_ur5_setup/tams_ur5_setup_description/urdf/tams_corner.urdf.xacro
included from: */src/tams/tams_ur5_setup/tams_ur5_setup_description/urdf/tams_ur5_setup.urdf.xacro
redefining global property: pi
when processing file: */src/tams/tams_ur5/tams_ur5_description/urdf/arm.urdf.xacro
included from: */src/tams/tams_ur5_setup/tams_ur5_setup_description/urdf/tams_ur5_setup.urdf.xacro
redefining global property: pi
when processing file: *src/tams/tams_ur5/tams_ur5_description/urdf/ur5.urdf.xacro
included from: */tams/tams_ur5/tams_ur5_description/urdf/arm.urdf.xacro
included from: */src/tams/tams_ur5_setup/tams_ur5_setup_description/urdf/tams_ur5_setup.urdf.xacro
xacro:include: unknown attribute(s): prefix
```
The warning message was written in `macro`

**Comment by v4hn** [comment]
Looks like the error trace is confusing (and probably wrong here, so it's a bug in xacro too :angel: )

Could you please verify [the additional prefix parameter here](https://github.com/TAMS-Group/tams_ur5/blob/master/tams_ur5_description/urdf/arm.urdf.xacro#L11) to be the culprit?
The warning should go away if you just remove the parameter there.

If that is the problem, the line
> when processing file: *src/tams/tams_ur5/tams_ur5_description/urdf/ur5.urdf.xacro

in the log is plain wrong and it would be great if you could file an issue in the xacro repository! :+1:

**Comment by lianghongzhuo** [comment]
Yes, the warning comes from that line.
